yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):

    def __str__(self):
        return self.title
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=10, null=True, blank=True, unique=True)
    description = models.TextField()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group

DISPLAY_LIMIT = 10


def index(request):
    posts = Post.objects.order_by('-pub_date')[:DISPLAY_LIMIT]
    template = 'posts/index.html'
    context = {
        'posts': posts,
        'title': 'Главная страница'
    }

    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')[:DISPLAY_LIMIT]
    context = {
        'group': group,
        'posts': posts
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" img src="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" img src="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" img src="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" img src="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
        {% block title %}base{% endblock %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>  

yatube/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="">
        <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Страница сообщества {{group.title}}{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>{{group.title}}</h1>
        <p>{{group.description}}</p>
        {% for post in posts %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>
                {{ post.text }}
            </p>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Yatube{% endblock %}
{% load static %}
{% block content %}
    <div class="container py-5">
        <h1>{{title}}</h1>
        {% for post in posts %}
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>
                {{ post.text }}
            </p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    </div>
{% endblock %}